/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  patch: [
    'patch/patch-10.1.48',
    'patch/update-10.0.576',
    /*'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    }, */
  ],
  guide: [{type: 'autogenerated', dirName: 'guide'}],
  organisations: [{type: 'autogenerated', dirName: 'organisations'}],
  creators: [
    {
      type: 'category',
      label: 'Créateurs de contenu',
      link: {
        type: 'doc',
        id: 'creators/creators',
      },
       items: [
        'creators/ltcloflam'
       ],
    }
  ],


};

export default sidebars;
