/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  guide: [
    'guide/introduction',
    {
      type: 'category',
      label: 'Les fondamentaux',
      link: {
        type: 'doc',
        id: 'guide/fondamentaux/fondamentaux',
      },
      items: [
        {
          type: 'category',
          label: 'L\'économie',
          link: {
            type: 'doc',
            id: 'guide/fondamentaux/economie/economie',
          },
          items: [
            'guide/fondamentaux/economie/villageois',
            'guide/fondamentaux/economie/ressource',
            'guide/fondamentaux/economie/centre-ville',
            'guide/fondamentaux/economie/trade'

          ],
        }
      ],
    }],
  organisations: [{ type: 'autogenerated', dirName: 'organisations' }],
  creators: [
    {
      type: 'category',
      label: 'Créateurs de contenu',
      link: {
        type: 'doc',
        id: 'creators/creators',
      },
      items: [
        'creators/zuka',
        'creators/the_eternal',
        'creators/ltcloflam',
      ],
    }
  ],


};

export default sidebars;
